# ---------------------------------------------------------
# *** JDBC configuration to fetch metadata ***

jdbcSettings:
  url: "jdbc:h2:./data/api-database"
  username: "sa"
  password: "password"
  driverClassName: "org.h2.Driver"

# ---------------------------------------------------------
# *** Basic/global configuration ***

# If you need to specify non-standard source directory, set the following setting as needed
#   - string value: the relative path from the project root directory.
outputDirectory: "src/main/java"

# The package name used when generating entity classes
#   - string value: full package name
packageName: "com.speakbuddy.service.soundreceiverapi.repository.models"

# If you need to generate JPA 1 compatible entity classes as well, set the following attributes
#   - boolean value: true if you need to generate JPA 1 compatible entities as well
jpa1SupportRequired: false
# The package to put JP 1 compatible entity classes.
#   - string value: full package name separate from the "packageName"
packageNameForJpa1: "com.example.entity.jpa1"

# If you'd like to have JSR-305 annotations in entity classes as well, set the following attribute
#   - boolean value: true if you need to generate Nonnull/Nullable annotation-wired entities as well
jsr305AnnotationsRequired: false

# If you want use primitive type instead of the boxing type(e.g: int <-> Integer), set the following attribute
# This will only take effect on non null fields
#   - boolean value: true if you want to use primitive type for non null fields
usePrimitiveForNonNullField: false

# ---------------------------------------------------------
# *** Table scan mode ***

# Set the scan mode (possible values: All / RuleBased)
#   - string value: 'All' (default) or 'RuleBased'
tableScanMode: 'All'

# If the "tableScanMode" is "RuleBased", the table scanner considers these rules
#   - array of TableScanRule objects
#     - tableName (string) / tableNames (array): string value that partially matches table names (case sensitive)
#tableScanRules:
#  - tableNames: ["foo_.*"]